#!/bin/bash
# Autonomous Task Processor - Runs in CI without human interaction
set -e

QUEUE_FILE=".ai-workspace/task-queue.json"
LOG_FILE=".ai-workspace/execution.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Get next task from queue
NEXT_TASK=$(jq -r '.queue[0] // empty' "$QUEUE_FILE")

if [ -z "$NEXT_TASK" ]; then
    log "✅ No tasks in queue. Done!"
    exit 0
fi

TASK_ID=$(echo "$NEXT_TASK" | jq -r '.id')
TASK_TITLE=$(echo "$NEXT_TASK" | jq -r '.title')
FILE_PATH=$(echo "$NEXT_TASK" | jq -r '.filePath')

log "🚀 Processing: $TASK_ID - $TASK_TITLE"

# Create feature branch
BRANCH_NAME="automation/${TASK_ID,,}-$(echo $TASK_TITLE | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | head -c 30)"
cd repos/mobile_dejtingapp
git checkout main
git pull origin main
git checkout -b "$BRANCH_NAME"

log "📝 Created branch: $BRANCH_NAME"

# Generate screen using template
python3 ../../scripts/generate-screen.py "$TASK_ID"

# Validate
flutter analyze "lib/screens/wizard/${FILE_PATH##*/}"

# Commit
git add "lib/screens/wizard/${FILE_PATH##*/}"
git commit -m "feat(onboarding): Add $TASK_TITLE ($TASK_ID)

Auto-generated by task queue processor"

# Push and create PR
git push origin "$BRANCH_NAME"
gh pr create --base main --head "$BRANCH_NAME" \
  --title "feat(onboarding): Add $TASK_TITLE ($TASK_ID)" \
  --body "Auto-generated from task queue. Ready for review."

log "✅ PR created for $TASK_ID"

# Update queue
cd ../..
jq --arg id "$TASK_ID" '
  .queue = (.queue | map(select(.id != $id))) |
  .completed += [(.queue[] | select(.id == $id)) + {completedAt: now | todate}]
' "$QUEUE_FILE" > "$QUEUE_FILE.tmp"
mv "$QUEUE_FILE.tmp" "$QUEUE_FILE"

log "✅ Task $TASK_ID completed"
